/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f7faf6',
        'on-tertiary-fixed-variant': '#464745',
        'tertiary-fixed-dim': '#c7c6c4',
        'secondary-fixed-dim': '#ffb869',
        primary: '#005440',
        'inverse-primary': '#84d6b9',
        'secondary-fixed': '#ffdcbb',
        'primary-fixed': '#a0f3d4',
        'on-tertiary-container': '#dddcd9',
        'on-secondary': '#ffffff',
        tertiary: '#484947',
        'outline-variant': '#bec9c3',
        'on-surface': '#181d1a',
        'on-secondary-fixed': '#2b1700',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#e0e3e0',
        'error-container': '#ffdad6',
        'surface-tint': '#086b53',
        'surface-container-high': '#e5e9e5',
        'surface-variant': '#e0e3e0',
        outline: '#6f7a74',
        'on-primary-fixed-variant': '#00513e',
        'on-tertiary-fixed': '#1a1c1a',
        'on-surface-variant': '#3f4944',
        'on-background': '#181d1a',
        'primary-container': '#0f6e56',
        'surface-bright': '#f7faf6',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#002117',
        'surface-container-low': '#f1f4f1',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'secondary-container': '#fdad4e',
        'primary-fixed-dim': '#84d6b9',
        'inverse-on-surface': '#eef2ee',
        'inverse-surface': '#2d312f',
        'tertiary-fixed': '#e3e2df',
        secondary: '#885200',
        surface: '#f7faf6',
        'tertiary-container': '#60615f',
        'on-primary-container': '#9aedcf',
        error: '#ba1a1a',
        'surface-container': '#ebefeb',
        'surface-dim': '#d7dbd7',
        'on-secondary-fixed-variant': '#673d00',
        'on-secondary-container': '#704200',
        'success-green': '#1e7e34',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        xs: '4px',
        'margin-desktop': '40px',
        md: '16px',
        gutter: '16px',
        sm: '8px',
        'margin-mobile': '16px',
        base: '4px',
        lg: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      addUtilities({
        '.card-flat': {
          backgroundColor: '#ffffff',
          borderWidth: '1px',
          borderColor: '#bec9c3',
          borderRadius: '0.5rem',
        },
      });
    },
  ],
};
